### ISSUE TITLE
Unable to remove renderer

### ISSUE THREAD

**Issue by punyidea** [m4-k131/dream-cli#3]
I get the following traceback after adding three renderers, and attempting to remove one:

`Traceback (most recent call last):
  File "C:/Users/42/PycharmProjects/dream-cli/dreamcli.py", line 1086, in <module>
    main()
  File "C:/Users/42/PycharmProjects/dream-cli/dreamcli.py", line 1083, in main
    main_menu()
  File "C:/Users/42/PycharmProjects/dream-cli/dreamcli.py", line 117, in main_menu
    renderer_menu()
  File "C:/Users/42/PycharmProjects/dream-cli/dreamcli.py", line 405, in renderer_menu
    renderer_menu()
  File "C:/Users/42/PycharmProjects/dream-cli/dreamcli.py", line 405, in renderer_menu
    renderer_menu()
  File "C:/Users/42/PycharmProjects/dream-cli/dreamcli.py", line 405, in renderer_menu
    renderer_menu()
  File "C:/Users/42/PycharmProjects/dream-cli/dreamcli.py", line 401, in renderer_menu
    remove_renderer_menu()
  File "C:/Users/42/PycharmProjects/dream-cli/dreamcli.py", line 415, in remove_renderer_menu
    '['+str(settings.c_settings['renderers'][i]['layer']['f_channel'])
TypeError: string indices must be integers`

**Comment by m4-k131** [comment]
Should be fixed now.

**Comment by m4-k131** [comment]
Closing this issue unless there is something i missed.
